### PR TITLE
Insetter constraint helper

### PR DESCRIPTION
**Pull request by mzgreen**
This change introduces `InsetterConstraintHelper` as an alternative way for using Insetter with  ConstraintLayout.

Addresses https://github.com/chrisbanes/insetter/issues/20

### CODE REVIEW

**Comment by mzgreen** [comment]
@googlebot I signed it!

**Comment by chrisbanes** [comment]
Thanks! Would you mind rebasing on top of master? I've submitted `InsetterConstraintLayout` so you can safely use all of the utils.

**Comment by mzgreen** [comment]
Done, it's now rebased on top of master.

There are 2 things I would like to discuss:
1. Name - do you think `InsetterConstraintHelper` is ok? Other helpers that are shipped with `ConstraintLayout` doesn't use `ConstraintHelper` suffix. See `Group` or `Layer` helpers.

2. I found one issue with this helper that I'm not sure how to fix without changing `applyInsetsToView`. It should be possible to reference the same view in multiple different constraint helpers (I'm not sure if it's documented anywhere, I heard this information from Nicolas Roard). Right now it's not possible with `InsetterConstraintHelper`. 
Let's say we add 2 `InsetterConstraintHelper`s in xml, one will be modifying only `paddingTop` and second one `paddingBottom` and we reference the same view in both of them. Both helpers will create a `tag` containing initial `ViewState` inside `onAttachedToWindow`. That means that `ViewState` will contain `paddingTop = 0` and `paddingBottom = 0` for both helpers. Now first helper is executed and it correctly modifies `paddingTop` then the second helper comes in and modifies `paddingBottom` but since second helper `ViewState` contained `paddingTop = 0` it'll overwrite the `paddingTop` value. The result is that only the bottommost helper in xml will have an effect on the view.
I'm not sure how to fix it without sacrificing the simplicity. We can't just use `view.padding` instead of using initial `ViewState` because `onApplyWindowInsets` can be called multiple times and it would result in padding adding up each time.
Let me know if you have an idea how to fix it or if we can leave this as is for now.

**Comment by chrisbanes** [comment]
I'm not sure what's happened, but the commit list is duplicated. Anyway:

1) Yeah `InsetterConstraintHelper` sounds good to me.
2) Hmmm, we could make `applyInsetsToView()` use the current padding value as the source. That way each would only be layering on top of each other. Definitely needs to some tests though (I've just submitted the skeleton framework for tests in #25).

**Comment by mzgreen** [comment]
Not sure what happened with commit list, I just rebased onto master and pushed it.

I added tests.

And I fixed the issue I wrote before. It turns out that it's not as simple as just using current padding value as the source. It would work fine if we assume that  we'll get insets only once. But there is a test case for changing insets. And if we use current padding value as a source and then change insets then paddings will add up instead of being overwritten by the new insets. That's why I added a workaround for this which saves previously applied insets and compares them with the ones that are being applied now and if they differ then we want to overwrite paddings. If they are the same then it means that the view is probably added to more than 1 helper in xml and some other helper already used the same insets to apply some paddings and in this case we want paddings to add up. I hope I explained it clearly and the proposed solution is ok for you.

**Pull request merged**
