### PR TITLE
Added extensions for padding and margins

### PR DESCRIPTION
**Pull request by mercuriy94**
Convenient extensions for applying insets, helping to avoid boilerplate code

### CODE REVIEW

**Comment by mercuriy94** [comment]
@googlebot I signed it!

**Comment by chrisbanes** [comment]
Thanks, but I'm going to hold off adding methods like this until we can use the new [`WindowInsets[Compat].Type`](https://developer.android.com/reference/android/view/WindowInsets.Type) values:

`applySystemWindowInsetsToPadding()` then becomes `applyInsetsToPadding(type: Int)` and is much more flexible.

I'll probably change a lot of the API once we can use `Type`, so I don't want to commit to new API right now.

WDYT?

**Comment by chrisbanes** [comment]
Although we could merge this, and then deprecate later (in the re-write).

**Comment by mercuriy94** [comment]
Hello, yes, I agree!
We will have to change api in the future.
But I think that now it makes sense to adopt pr in order to give the opportunity to use convenient extenssions in current projects.
In the future, when the api changes, a new version will be released, but for those who use the old version, support will remain.

**Pull request merged**
